### ISSUE TITLE
Rename references to pixi-react / @pixi/react

### ISSUE THREAD

**Issue by baseten** [pixijs/pixi-react#371]
# Info

We are looking to keep consistency with other 1st party projects naming conventions. This means renaming internal and external references to react-pixi

- `react-pixi` - > `pixi-react`
- `@inlet/react-pixi` -> `@pixi/react`

# Tasks

- [ ] Update readme
- [ ] Update documentation site
  - [ ] Speak to John about a new logo
  - [ ] Update any references in examples
  - [ ] Update site name (TBD)
- [ ] Update package.json to `@pixi/react`
- [ ] Update repo name to `pixi-react`
- [ ] Update any in code references
