### ISSUE TITLE
Add support for core plugins

### ISSUE THREAD

**Issue by baseten** [pixijs/pixi-react#374]
# Info

We are aiming to get all of our 1st party plugins available in the react ecosystem. This means adding several missing packages

# Tasks

- [ ] Add Spine
- [ ] Add Particles
- [ ] Add Animate
- [ ] Add Graphics-smooth
- [ ] Add pixi-gif
- [ ] Add pixi-html-text
- [ ] Add pixi-filters (may not be needed as filters in general work)
- [ ] Add pixi-ui (under development)
- [ ] Add pixi-layout (under development)

**Comment by simjega** [comment]
+ 1 to this! I need graphics smooth right now.

**Comment by artokun** [comment]
I got one for SmoothGraphics built up
```tsx
import { Container } from "@pixi/display";
import {
  SmoothGraphics as Graphics,
  type SmoothGraphicsGeometry,
} from "@pixi/graphics-smooth";
import {
  applyDefaultProps,
  type Container as IContainer,
  PixiComponent,
} from "@pixi/react";

type SmoothGraphicsOptions = {
  draw: (g: Graphics) => Graphics;
  geometry?: SmoothGraphicsGeometry;
};

export type SmoothGraphicsProps = typeof IContainer.defaultProps &
  SmoothGraphicsOptions;

export const GraphicsSmooth = PixiComponent<SmoothGraphicsProps, Container>(
  "GraphicsSmooth",
  {
    create: ({ geometry }) => {
      const container = new Container();
      const g = geometry ? new Graphics(geometry) : new Graphics();
      container.addChild(g);
      return container;
    },
    applyProps: (container, prevProps, nextProps) => {
      const { draw, geometry: _, ...props } = nextProps;
      const instance = container.children[0] as Graphics;

      applyDefaultProps(container, prevProps, props);

      if (prevProps.draw !== draw && typeof draw === "function") {
        draw.call(instance, instance);
      }

      return container;
    },
  },
);
```

**Comment by woody146** [comment]
Waiting for pixi-ui and pixi-layout

**Comment by StreakingMan** [comment]
Waiting for spine

**Comment by mterczynski** [comment]
I found these 2 code examples related to pixi-spine:

https://gist.github.com/ascorbic/f01009247f859f0d76b8b92d34ae87bd
https://github.com/pixijs/pixi-react/pull/174

I didn't make any of them work in my project, but hopefully this helps someone

**Comment by trezy** [comment]
Closing since v7 is no longer the latest version and will only receive security updates moving forward.
