### ISSUE TITLE
Launch Tasks

### ISSUE THREAD

**Issue by baseten** [pixijs/pixi-react#375]
# Info

Below is a list of open issues / tasks that need to be complete before our global launch on the 30th

# Tasks

- [x] All P1/2 tickets are complete
- [x] v7 support
- [x] Renamed to `pixi-react` and `@pixi/react`
- [x] Documentation site is updated
  - [x] Examples work with v7
  - [x] References to `react-pixi` replaced with `pixi-react`
- [x] README is updated
- [x] Website published to gh-pages
- [x] Official release on npm
- [x] Release notes on Github 
- [x] Announcement post prepared
